config/routes.rb
Rails.application.routes.draw do

  resources :tickets, only: [:new, :create, :edit, :update] do
    member do
      get :cancel
      get :complete
    end
  end

  devise_for :admins
  root 'home#index'

  namespace :admin do
    resources :tickets, only: [:new, :create, :edit, :update, :destroy, :index] do
      collection do
        get :open
        get :on_hold
        get :closed
        get :search
      end
    end
  end

end

app/models/ticket.rb
class Ticket < ActiveRecord::Base

  include PgSearch

  multisearchable :against => [:name, :customer_email, :subject, :description]

  belongs_to :department
  belongs_to :admin
  belongs_to :status

  has_many :replies

  validates_presence_of :name, :department, :subject, :description
  validates :customer_email, format: /@/

  before_create :generate_ref_num
  before_create :set_base_status

  accepts_nested_attributes_for :replies

  def self.unassigned
    self.where(admin: nil)
  end

  def self.open_tickets
    self.joins(:status).where("statuses.name IN ('Waiting for Staff Response', 'Waiting for Customer', 'On Hold')")
  end

  def self.on_hold
    self.joins(:status).where("statuses.name = 'On Hold'")
  end

  def self.closed
    self.joins(:status).where("statuses.name IN ('Cancelled', 'Completed')")
  end

  def to_param
    ref_num
  end

  private

  def generate_ref_num
    self.ref_num = ReferenceNumber.new.generate
  end

  def set_base_status
    self.status = Status.waiting_for_staff_response
  end

end

app/controllers/admin/tickets_controller.rb
class Admin

  class TicketsController < AdminController
    before_action :set_ticket, only: [:show, :edit, :update, :destroy]
    before_action :set_section

    respond_to :html

    def index
      @tickets = Ticket.all.includes(:admin, :department).unassigned
      list_tickets
    end

    def open
      @section = params[:action]
      @tickets = Ticket.all.includes(:admin, :department).open_tickets
      list_tickets
    end

    def on_hold
      @section = params[:action]
      @tickets = Ticket.all.includes(:admin, :department).on_hold
      list_tickets
    end

    def closed
      @section = params[:action]
      @tickets = Ticket.all.includes(:admin, :department).closed
      list_tickets
    end

    def search
      @tickets = TicketSearcher.new(params[:q], limit: params[:page_limit]).search
    end

    def show
      respond_with(@ticket)
    end

    def new
      @ticket = Ticket.new
      respond_with(@ticket)
    end

    def edit
    end

    def create
      @ticket = Ticket.new(ticket_params)
      if @ticket.save
        CustomerMailer.new_ticket_email(@ticket).deliver
        flash[:notice] = 'Your feedback was successfully saved.'
        respond_with(@ticket, :status => :created, :location => @ticket) do |format|
          format.html { redirect_to edit_admin_ticket_path(@ticket) }
        end
      else
        respond_with(@ticket.errors, :status => :unprocessable_entity) do |format|
          format.html { render :action => :new }
        end
      end
    end

    def update
      tickt_par = ticket_params.dup
      tickt_par['replies_attributes'] = Hash[tickt_par['replies_attributes'].reject { |k, v| v['description'].blank? }] if tickt_par['replies_attributes']
      @ticket.update(tickt_par)
      if @ticket.save
        send_email_if_replied(tickt_par['replies_attributes'])
        flash[:notice] = 'Your feedback was successfully saved.'
        respond_with(@ticket, :status => :created, :location => @ticket) do |format|
          format.html { redirect_to edit_admin_ticket_path(@ticket) }
        end
      else
        respond_with(@ticket.errors, :status => :unprocessable_entity) do |format|
          format.html { render :action => :new }
        end
      end
    end

    def destroy
      @ticket.destroy
      respond_with(@ticket)
    end

    private

      def send_email_if_replied(reply_params)
        if reply_params
          CustomerMailer.ticket_updated_email(@ticket).deliver
        end
      end

      def set_section
        @section = nil
      end

      def list_tickets
        respond_to do |format|
          format.html { render :index }
          format.json { render json: @tickets }
        end
      end

      def set_ticket
        @ticket = Ticket.find_by(ref_num: params[:id]) or raise "Not found"
      end

      def ticket_params
        params.require(:ticket).permit(:name, :customer_email, :department_id, :admin_id, :subject, :description, :status_id, replies_attributes: [:description, :admin_id])
      end
  end

end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:edit, :update, :complete, :cancel]

  respond_to :html

  def show
    respond_with(@ticket)
  end

  def new
    @ticket = Ticket.new
    respond_with(@ticket)
  end

  def edit
  end

  def create
    @ticket = Ticket.new(ticket_params)
    @ticket.save
    if @ticket.save
      CustomerMailer.new_ticket_email(@ticket).deliver

      flash[:notice] = 'Your feedback was successfully saved.'
      respond_with(@ticket, :status => :created, :location => @ticket) do |format|
        format.html { redirect_to edit_ticket_path(@ticket) }
      end
    else
      respond_with(@ticket.errors, :status => :unprocessable_entity) do |format|
        format.html { render :action => :new }
      end
    end
  end

  def update
    @ticket.update(reply_params)

    respond_to do |format|
      if @ticket.save
        flash[:notice] = 'Your feedback was successfully saved.'
        format.html { redirect_to edit_ticket_path(@ticket) }
      else
        flash[:notice] = 'Some error prevented the form to submit.'
        format.html { render 'edit' }
      end
    end
  end

  def cancel
    @ticket.update(status: Status.cancelled)
    redirect_to edit_ticket_path(@ticket)
  end

  def complete
    @ticket.update(status: Status.completed)
    redirect_to edit_ticket_path(@ticket)
  end

  private
    def set_ticket
      @ticket = Ticket.find_by(ref_num: params[:id]) or raise "Not found"
    end

    def ticket_params
      params.require(:ticket).permit(:name, :customer_email, :department_id, :subject, :description)
    end

    def reply_params
      params.require(:ticket).permit(replies_attributes: [:description, :customer_email])
    end
end

app/views/tickets/_form.html.haml
.row
  .col-sm-6
    = bootstrap_form_for @ticket do |f|
      - if @ticket.errors.any?
        %p
          #{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved.
          %br
          Please check this form before submitting again.

      = f.text_field :name, label: "Please enter your full name"
      = f.email_field :customer_email, label: "Your e-mail address"
      = f.collection_select :department_id, Department.all, :id, :name

      = f.text_field :subject
      = f.text_area :description, label: "Description of the enquiry"

      .actions
        = f.submit 'Create ticket'

app/views/tickets/edit.html.haml
%h2 Your Ticket

%p
  %b Ticket reference number:
  = @ticket.ref_num

%p
  %b Name:
  = @ticket.name
%p
  %b Customer email:
  = @ticket.customer_email
%p
  %b Department:
  = @ticket.department.name
%p
  %b Staff in charge:
  = @ticket.admin.try(:name) || "(Currently unassigned)"
%p
  %b Description:
  %br
  = nl2br @ticket.description
%p
  %b Status:
  = @ticket.status.name

- if @ticket.replies.length > 0
  %p
    %b Replies
  .panel.panel-default
    - @ticket.replies.each do |reply|
      .panel-body
        .small
          = reply.created_at
          by #{reply.author}
        = reply.description

- unless @ticket.status.closed?
  .row
    .col-sm-6
      = bootstrap_form_for @ticket do |f|

        = f.fields_for :replies, @ticket.replies.build do |f|
          - if @ticket.errors.any?
            - f.object.valid?
            %p
              #{pluralize(@ticket.errors.count, "error")} prohibited this ticket from being saved.
              %br
              Please check this form before submitting again.

          = f.hidden_field :customer_email, value: @ticket.customer_email
          = f.text_area :description

          .actions
            = f.submit 'Send update'

            = link_to "Mark as complete", complete_ticket_path(@ticket), data: { confirm: 'Are you sure?' }
            |
            = link_to "Cancel", cancel_ticket_path(@ticket), data: { confirm: 'Are you sure?' }

app/views/tickets/new.html.haml
%h1 Create a new ticket

= render 'form'

app/views/tickets/show.html.haml
%h2 Your Ticket

%p
  %b Ticket reference number:
  = @ticket.ref_num

%p
  %b Name:
  = @ticket.name
%p
  %b Customer email:
  = @ticket.customer_email
%p
  %b Department:
  = @ticket.department.name
%p
  %b Staff in charge:
  = @ticket.admin.try(:name) || "(Currently unassigned)"
%p
  %b Description:
  = @ticket.description
%p
  %b Status:
  = @ticket.status.name