config/routes.rb
Rails.application.routes.draw do

  resources :tickets, only: [:new, :create, :edit, :update] do
    member do
      get :cancel
      get :complete
    end
  end

  devise_for :admins
  root 'home#index'

  namespace :admin do
    resources :tickets, only: [:new, :create, :edit, :update, :destroy, :index] do
      collection do
        get :open
        get :on_hold
        get :closed
        get :search
      end
    end
  end

end

app/views/layouts/admin.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "HostTastic"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "admin", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "admin"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "HostTastic Admin", admin_tickets_path, class: 'navbar-brand'
        .navbar-collapse.collapse.navbar-responsive-collapse
          %ul.nav.navbar-nav
            = show_menu_items.html_safe
            %li= link_to "Logout", destroy_admin_session_path, method: :delete

          %form.navbar-form.navbar-right.search
            %input.form-control{placeholder: "Find ticket", type: "text", name: 'ticket', class: 'ajax-results', :"data-path" => '/admin/tickets/search', :"data-redirect-to" => "/admin/tickets/{id}/edit" }
    #page-wrap

      .container
        .row
          #page-container.col-lg-12
            = bootstrap_flash
            = yield

        %footer
          %p &copy; Company 2014

app/views/layouts/application.html.haml
!!! 5
%html(lang="en")
  %head
    %meta(charset="utf-8")
    %meta(http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1")
    %meta(name="viewport" content="width=device-width, initial-scale=1.0")
    %title= content_for?(:title) ? yield(:title) : "HostTastic"
    = csrf_meta_tags
    / Le HTML5 shim, for IE6-8 support of HTML elements
    /[if lt IE 9]
      = javascript_include_tag "//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js"
    = stylesheet_link_tag "application", :media => "all"
    = favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144'
    = favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114'
    = favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72'
    = favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png'
    = favicon_link_tag 'favicon.ico', :rel => 'shortcut icon'
    = javascript_include_tag "application"

  %body
    .navbar.navbar-default.navbar-static-top
      .container
        %button.navbar-toggle(type="button" data-toggle="collapse" data-target=".navbar-responsive-collapse")
          %span.icon-bar
          %span.icon-bar
          %span.icon-bar
        = link_to "HostTastic", root_path, class: 'navbar-brand'

    #page-wrap

      .container
        .row
          #page-container.col-lg-12
            = bootstrap_flash
            = yield

        %footer
          %p &copy; Company 2014
          %p= link_to "Enter the admin area", admin_tickets_path